web:
  build: .
  command: bundle exec rackup --host 0.0.0.0 -p 3000
  links:
    - db
    - etcd
  volumes:
    - .:/usr/src/app
  volumes_from:
    - bundle
  ports:
    - "3000:3000"

db:
  image: klaemo/couchdb

etcd:
  image: elcolio/etcd
  command: -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls=http://0.0.0.0:2379

bundle:
  image: busybox
  volumes:
    - /bundle
